### ISSUE TITLE
Invalid column name 'RetentionPolicy'

### ISSUE THREAD

**Issue by mmb5** [MicrosoftDocs/cloud-adoption-framework#1045]
I received the following error when running the Migrator tool:

`[Error  @09:30:59.687] Microsoft.TeamFoundation.Framework.Server.TeamFoundationServicingException:  Line 9 Error: Invalid column name 'RetentionPolicy'.
                       Invalid column name 'RetentionPolicy'. ---> System.Data.SqlClient.SqlException: Invalid column name 'RetentionPolicy'.
                       Invalid column name 'RetentionPolicy'.
                          at Microsoft.TeamFoundation.Framework.Server.TeamFoundationSqlResourceComponent.MapException(SqlException ex, QueryExecutionState queryState)
                          at Microsoft.TeamFoundation.Framework.Server.TeamFoundationSqlResourceComponent.HandleException(Exception exception)
                          at Microsoft.TeamFoundation.Framework.Server.TeamFoundationSqlResourceComponent.ExecuteCommand(ExecuteType executeType, CommandBehavior behavior, String performanceGroupName)
                          at Microsoft.VisualStudio.Services.CircuitBreaker.Command.<>c__DisplayClass7_0.<Execute>b__0()
                          at Microsoft.VisualStudio.Services.CircuitBreaker.CommandAsync.<Execute>d__30.MoveNext()
                       --- End of stack trace from previous location where exception was thrown ---
                          at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                          at Microsoft.VisualStudio.Services.CircuitBreaker.CommandAsync.<Execute>d__30.MoveNext()
                       --- End of stack trace from previous location where exception was thrown ---
                          at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                          at Microsoft.VisualStudio.Services.CircuitBreaker.Command.Execute(Action run, Action fallback)
                          at Microsoft.TeamFoundation.Framework.Server.DatabaseCircuitBreaker.ExecuteCommandWithBaseCircuitBreaker(ExecuteType executeType, CommandBehavior behavior, String performanceGroupName)
                          at Microsoft.TeamFoundation.Framework.Server.SqlScriptResourceComponent.ExecuteStatementImpl(String statement, SqlParameter[] sqlParameters, ExecutionType executionType, Boolean logStatementInfo, Int32 sqlCommandTimeout)
                          --- End of inner exception stack trace ---
                          at Microsoft.TeamFoundation.Framework.Server.SqlScriptResourceComponent.ExecuteStatementImpl(String statement, SqlParameter[] sqlParameters, ExecutionType executionType, Boolean logStatementInfo, Int32 sqlCommandTimeout)
                          at Microsoft.TeamFoundation.Build2.Server.Extensions.PipelineRetentionPolicyValidation.CountPipelinesWithRetentionPolicy(DataImportValidationContext validationContext, Guid[] projectIds)
                          at Microsoft.TeamFoundation.Build2.Server.Extensions.PipelineRetentionPolicyValidation.Run(DataImportValidationContext validationContext, String& message)
                          at Microsoft.TeamFoundation.Framework.Server.DataImport.DataImportValidator.Run(DataImportValidationType filter)
`

**Comment by ckittel** [comment]
To be clear, what "Migrator tool" are you referring to here?  Do you have a link to share on the Cloud Adoption Framework site for it?  Want to make sure this issue was opened up in the right repo so that the right 👀 see it.

**Comment by ckittel** [comment]
This is the open source issue tracker for the [Cloud Adoption Framework])https://aka.ms/caf] content on Microsoft Learn, which does not support the Azure DevOps Migration tool. This tool is however supported by Microsoft through a customer support case.

Please reach out to the support team at https://aka.ms/AzureDevOpsImportSupport. You can see more about support and troubleshooting options for this tool @ <https://learn.microsoft.com/azure/devops/migrate/migration-troubleshooting?view=azure-devops#import-failures>

I'm going to have to close this issue in the Cloud Adoption Framework, as it's unable to be resolved here.

#please-close
